version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cakephp-app
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: cakephp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root-password}
      MYSQL_DATABASE: ${DB_DATABASE:-app}
      MYSQL_USER: ${DB_USER:-username}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "${DB_PORT:-3306}:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_HOST: ${DB_HOST:-mysql}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root-password}
    ports:
      - "8081:80"
    depends_on:
      - mysql
